name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "scuttlebutt/**"
      - "scuttlebutt-*/**"


env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check (fmt, dependency check, clippy, test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ubuntu packages
        if: always() && steps.modified.outputs.rust_src == 'true'
        run: sudo apt-get -y install protobuf-compiler python3 python3-pip
      - name: Install rustup
        if: steps.modified.outputs.rust_src == 'true'
        run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
      - name: Setup stable Rust Toolchain
        if: steps.modified.outputs.rust_src == 'true'
        run: rustup show
        working-directory: ./chitchat
      - name: Setup nightly Rust Toolchain (for rustfmt)
        if: steps.modified.outputs.rust_src == 'true'
        run: rustup toolchain install nightly
      - name: Setup cache
        if: steps.modified.outputs.rust_src == 'true'
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./chitchat -> target"
      - name: cargo clippy
        if: always() && steps.modified.outputs.rust_src == 'true'
        run: cargo clippy --workspace --tests --all-features
        working-directory: ./chitchat
      - name: rustfmt
        if: always() && steps.modified.outputs.rust_src == 'true'
        run: cargo +nightly fmt --all -- --check
        working-directory: ./chitchat
