name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "chitchat/**"
      - "chitchat-*/**"


env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check (fmt, dependency check, clippy, test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ubuntu packages
        run: sudo apt-get -y install protobuf-compiler python3 python3-pip
      - name: Install rustup
        run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
      - name: Setup stable Rust Toolchain
        run: rustup show
        working-directory: ./chitchat
      - name: Setup nightly Rust Toolchain (for rustfmt)
        run: rustup toolchain install nightly
      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"
      - name: cargo clippy
        run: cargo clippy --workspace --tests --all-features
        working-directory: ./chitchat
      - name: rustfmt
        run: cargo +nightly fmt --all -- --check
        working-directory: ./chitchat
      - name: chitchat-test
        run: cargo build
        working-directory: ./chitchat-test
